### PR TITLE
Use Meeko to transform pdbqt to rdkit.Mol

### PR DESCRIPTION
**Pull request by davidoskky**
This addresses issue #8, I believe that this changes however force upgrading to Meeko v0.50.
Some automatic formatting through black has been introduced; if you prefer I may undo the change.

I added one test which makes sure the function works when operating on the pdbqt file provided in #8.

Let me know if this is alright or if something should be changed or adapted.
I did not test if these changes affect the boron adjustment procedure.

### CODE REVIEW

**Comment by DrrDom** [comment]
Thank you for the contribution!
The current easydock version is already adapted to the interface of the recent meeko version. However, it is always better to simplify the code and remove workaround functions.
The function `fix_pdbqt`, which was removed, did also some other staff rather then solve attachment point issues, because meeko created PDBQT files which did not fully correspond to the PDB format (shifted atom labels and numbers) and therefore some other issues occurred. We'll try to find those bad examples to test the new implementation before accepting it.

**Comment by davidoskky** [comment]
Indeed, you can send the examples here or I can provide you with an email address if you prefer. If you wish, I can take care of fixing those issues.
I'll be pending of some pdbqt examples or specific meeko conversion problems which you may provide to adjust this PR.

**Comment by DrrDom** [comment]
Did this code work for you? Meeko 0.5.0 gives me an error importing `PDBQTWriterLegacy`:
```python
from meeko import PDBQTWriterLegacy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'PDBQTWriterLegacy' from 'meeko' (/home/pavlop/anaconda3/envs/vina_cache/lib/python3.9/site-packages/meeko/__init__.py)
```
For some reason I had to use a full import path.
```python
from meeko.writer import PDBQTWriterLegacy
```
After that other errors occurred:
```
Warning. Incorrect mol object to convert to pdbqt. Continue. 
Traceback (most recent call last):
Warning. Incorrect mol object to convert to pdbqt. Continue. 
  File "/home/pavlop/python/easydock/easydock/preparation_for_docking.py", line 47, in mk_prepare_ligand
    for setup in mol_setups:
Traceback (most recent call last):
TypeError: 'NoneType' object is not iterable
  File "/home/pavlop/python/easydock/easydock/preparation_for_docking.py", line 47, in mk_prepare_ligand
    for setup in mol_setups:
TypeError: 'NoneType' object is not iterable
```
If this code works for you, I'll have to check it once more to understand why it does not work for me. If it does not work, please fix these issues.

**Comment by davidoskky** [comment]
I just tested again on a clean environment:

```
name: easydock
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.20
  - rdkit
  - scipy
  - vina
  - dask
  - distributed
  - pip:
      - -e .
      - meeko
```

The code does work for me without problems, I tested it on a small batch of ligands and the resulting sdf file definitely contains a set of docked ligands.

**Comment by DrrDom** [comment]
I found a mistake in my configuration. This version passed all tests successfully. It seems that we could not find some examples for which some specific fixes were implemented, but it seems to be rare cases. A typical previous error was reported here - https://github.com/forlilab/Meeko/issues/3. Now it is solved.

Before accepting the PR, I would like to ask you to revert the commit with formatting changes. If we would reformat code, it should be done in all modules to make changes consistent and this should not be mixed with other changes.

Thank you for the contribution!

**Comment by davidoskky** [comment]
Indeed, I reverted the formatting.
Just to be sure I run the test as well as a small docking sample and everything seems to work smoothly.

I'm happy I could help, I find this interface quite useful when docking large libraries of molecules.

**Pull request merged**
